apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: backend-eks-prod
  region: us-east-1
  version: "1.29"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single   # use HighlyAvailable for large prod

managedNodeGroups:
  - name: backend-ng
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 20
    privateNetworking: true
    iam:
      withAddonPolicies:
        ecr: true
        cloudWatch: true
